Repository Friend-LGA/msu_course_cpp_323, pull requests merged in 2021-10, with the labels that each got.

#26 robert_gaisin/task_01
  01_hello_world/robert_gaisin/README.md
  01_hello_world/robert_gaisin/hello_world
  01_hello_world/robert_gaisin/hello_world.cpp
  01_hello_world/robert_gaisin/hello_world.png
Labels: task_01

#13 tevfik_aksoy/task_02
  02_knight_and_princess/tevfik_aksoy/graph.json
  02_knight_and_princess/tevfik_aksoy/main
  02_knight_and_princess/tevfik_aksoy/main.cpp
Labels: task_02

#49 anton_potapov/task_02
  02_knight_and_princess/anton_potapov/README.md
  02_knight_and_princess/anton_potapov/a.out
  02_knight_and_princess/anton_potapov/graph.json
  02_knight_and_princess/anton_potapov/graph_create.cpp
Labels: task_02, task_03
