Repository Friend-LGA/msu_course_cpp_323, pull requests merged in 2021-12, with the labels that each got.

#113 nikolai_chernyshov/task 04
  nikolai_chernyshov/README.md
  nikolai_chernyshov/graph.json
  nikolai_chernyshov/main.cpp
  nikolai_chernyshov/main.o
Labels: task_04

#53 tamara_gadieva/task_02
  tamara_gadieva/README.md
  tamara_gadieva/Screenshot.png
  tamara_gadieva/graph.cpp
  tamara_gadieva/graph.hpp
  tamara_gadieva/graph_json
  tamara_gadieva/hello_world
  tamara_gadieva/hello_world.cpp
  tamara_gadieva/main
  tamara_gadieva/main.cpp
Labels: task_02, task_03

#66 anton_potapov/task_04
  anton_potapov/README.md
  anton_potapov/a.out
  anton_potapov/graph.hpp
  anton_potapov/graph.json
  anton_potapov/graph_create.cpp
  anton_potapov/graph_generator.hpp
Labels: task_04

#115 novikov_dmitry/task_06
  novikov_dmitry/graph.cpp
  novikov_dmitry/graph_generator.cpp
  novikov_dmitry/graph_generator.hpp
  novikov_dmitry/main.cpp
Labels: task_06

#57 alexander_setyaev/task_02
  setyaev_alexander/README.md
  setyaev_alexander/graph.cpp
  setyaev_alexander/graph.json
  setyaev_alexander/hello_world
  setyaev_alexander/hello_world.cpp
  setyaev_alexander/scrin.png
Labels: task_02, task_03

#88 Dana stepina/task 04
  dana_stepina/Makefile
  dana_stepina/graph.cpp
  dana_stepina/graph.hpp
  dana_stepina/graph.json
  dana_stepina/graph_generator.cpp
  dana_stepina/graph_generator.hpp
  dana_stepina/graph_printer.cpp
  dana_stepina/graph_printer.hpp
  dana_stepina/main
  dana_stepina/main.cpp
Labels: task_04

#124 roman_kuprii/task 06
  roman_kuprii/Makefile
  roman_kuprii/graph.cpp
  roman_kuprii/graph.hpp
  roman_kuprii/graph_generation.cpp
  roman_kuprii/graph_generation.hpp
  roman_kuprii/graph_generation_controller.cpp
  roman_kuprii/graph_generation_controller.hpp
  roman_kuprii/graph_generator.cpp
  roman_kuprii/graph_generator.hpp
  roman_kuprii/logging_helping.hpp
  roman_kuprii/main.cpp
  roman_kuprii/prog
Labels: task_06

#62 robert_gaisin/task_04
  robert_gaisin/graph_task_02.json
  robert_gaisin/graph_task_03.json
  robert_gaisin/grf
  robert_gaisin/main.cpp
Labels: task_04

#123 tevfik_aksoy/task_06
  tevfik_aksoy/graph_generator.cpp
  tevfik_aksoy/graph_generator.hpp
  tevfik_aksoy/main
Labels: task_06

#126 kirill_tolstobrov/task_05
  .gitignore
  kirill_tolstobrov/graph.cpp
  kirill_tolstobrov/graph.hpp
  kirill_tolstobrov/graph.json
  kirill_tolstobrov/graph_generator.cpp
  kirill_tolstobrov/graph_generator.hpp
  kirill_tolstobrov/graph_printer.cpp
  kirill_tolstobrov/graph_printer.hpp
  kirill_tolstobrov/logger.cpp
  kirill_tolstobrov/logger.hpp
  kirill_tolstobrov/main.cpp
  kirill_tolstobrov/prog
Labels: task_05

#118 nikolay_arbuzov/task03
  nikolay_arbuzov/Makefile
  nikolay_arbuzov/graph.json
  nikolay_arbuzov/hello_world
  nikolay_arbuzov/hello_world.cpp
  nikolay_arbuzov/main
  nikolay_arbuzov/main.cpp
  nikolay_arbuzov/screenshot.png
Labels: task_02, task_03

#128 shamil_latypov/task_05
  .gitignore
  shamil_latypov/graph.cpp
  shamil_latypov/graph.hpp
  shamil_latypov/graph_generator.cpp
  shamil_latypov/graph_generator.hpp
  shamil_latypov/graph_printer.cpp
  shamil_latypov/graph_printer.hpp
  shamil_latypov/logger.cpp
  shamil_latypov/logger.hpp
  shamil_latypov/main
  shamil_latypov/main.cpp
  shamil_latypov/out.json
Labels: task_05

#130 Dana stepina/task 05
  .gitignore
  dana_stepina/graph.cpp
  dana_stepina/graph.hpp
  dana_stepina/graph.json
  dana_stepina/graph_generator.cpp
  dana_stepina/graph_generator.hpp
  dana_stepina/graph_printer.cpp
  dana_stepina/graph_printer.hpp
  dana_stepina/logger.cpp
  dana_stepina/logger.hpp
  dana_stepina/main
  dana_stepina/main.cpp
Labels: task_05

#133 nikolai_chernyshov/task_05
  .gitignore
  nikolai_chernyshov/Makefile
  nikolai_chernyshov/config.hpp
  nikolai_chernyshov/graph.cpp
  nikolai_chernyshov/graph.hpp
  nikolai_chernyshov/graph.json
  nikolai_chernyshov/graph_generator.cpp
  nikolai_chernyshov/graph_generator.hpp
  nikolai_chernyshov/graph_printer.cpp
  nikolai_chernyshov/graph_printer.hpp
  nikolai_chernyshov/logger.cpp
  nikolai_chernyshov/logger.hpp
  nikolai_chernyshov/main.cpp
  nikolai_chernyshov/main.o
Labels: task_05

#117 tamara_gadieva/task_04
  tamara_gadieva/graph.cpp
  tamara_gadieva/graph.hpp
  tamara_gadieva/graph.json
  tamara_gadieva/graph_json
  tamara_gadieva/main
  tamara_gadieva/main.cpp
Labels: task_04

#135 anton_gadzikovskiy/task_03
  anton_gadzikovskiy/a.exe
  anton_gadzikovskiy/graph_generator.cpp
Labels: task_03

#93 xieyu_wang/task_04
  xieyu_wang/Edge.cpp
  xieyu_wang/Edge.hpp
  xieyu_wang/Graph.cpp
  xieyu_wang/Graph.hpp
  xieyu_wang/Graph.json
  xieyu_wang/GraphGenerator.cpp
  xieyu_wang/GraphGenerator.hpp
  xieyu_wang/Vertex.cpp
  xieyu_wang/Vertex.hpp
  xieyu_wang/main
  xieyu_wang/main.cpp
Labels: task_04

#142 tamara_gadieva/task_05
  tamara_gadieva/config.cpp
  tamara_gadieva/config.hpp
  tamara_gadieva/graph.cpp
  tamara_gadieva/graph.hpp
  tamara_gadieva/graph.json
  tamara_gadieva/graph_generator.cpp
  tamara_gadieva/graph_generator.hpp
  tamara_gadieva/graph_printing.cpp
  tamara_gadieva/graph_printing.hpp
  tamara_gadieva/logger.cpp
  tamara_gadieva/logger.hpp
  tamara_gadieva/main
  tamara_gadieva/main.cpp
Labels: task_05

#137 kirill_tolstobrov/task_06
  kirill_tolstobrov/graph.cpp
  kirill_tolstobrov/graph_generator.cpp
  kirill_tolstobrov/graph_generator.hpp
  kirill_tolstobrov/prog
Labels: task_06

#144 nikolai_chernyshov/task_06
  nikolai_chernyshov/graph_generator.cpp
  nikolai_chernyshov/graph_generator.hpp
  nikolai_chernyshov/main.o
Labels: task_06

#136 anton_gadzikovskiy/task_04
  anton_gadzikovskiy/a.exe
  anton_gadzikovskiy/graph.json
  anton_gadzikovskiy/graph_generator.cpp
Labels: task_04

#147 nikolai_chernyshov/task_07
  nikolai_chernyshov/Makefile
  nikolai_chernyshov/graph_generation_controller.cpp
  nikolai_chernyshov/graph_generation_controller.hpp
  nikolai_chernyshov/graph_generator.cpp
  nikolai_chernyshov/graph_generator.hpp
  nikolai_chernyshov/main.cpp
  nikolai_chernyshov/main.o
Labels: task_07

#145 novikov_dmitry/task_08
  novikov_dmitry/graph_generation.cpp
  novikov_dmitry/graph_printer.cpp
  novikov_dmitry/graph_printer.hpp
  novikov_dmitry/graph_traversal_controller.cpp
  novikov_dmitry/graph_traversal_controller.hpp
  novikov_dmitry/graph_traverser.cpp
  novikov_dmitry/graph_traverser.hpp
  novikov_dmitry/main.cpp
Labels: task_08

#140 robert_gaisin/task_05
  .gitignore
  robert_gaisin/Makefile
  robert_gaisin/config.cpp
  robert_gaisin/config.hpp
  robert_gaisin/graph
  robert_gaisin/graph.cpp
  robert_gaisin/graph.hpp
  robert_gaisin/graph_generator.cpp
  robert_gaisin/graph_generator.hpp
  robert_gaisin/graph_printer.cpp
  robert_gaisin/graph_printer.hpp
  robert_gaisin/graph_task_03.json
  robert_gaisin/grf
  robert_gaisin/logger.cpp
  robert_gaisin/logger.hpp
  robert_gaisin/main.cpp
Labels: task_05

#139 tevfik_aksoy/task_08
  tevfik_aksoy/graph.cpp
  tevfik_aksoy/graph.hpp
  tevfik_aksoy/graph_printer.cpp
  tevfik_aksoy/graph_printer.hpp
  tevfik_aksoy/graph_traversal.cpp
  tevfik_aksoy/graph_traversal.hpp
  tevfik_aksoy/graph_traversal_controller.cpp
  tevfik_aksoy/graph_traversal_controller.hpp
  tevfik_aksoy/logger.hpp
  tevfik_aksoy/main
  tevfik_aksoy/main.cpp
Labels: task_08

#146 kirill_tolstobrov/task_07
  kirill_tolstobrov/graph_generation_controller.cpp
  kirill_tolstobrov/graph_generation_controller.hpp
  kirill_tolstobrov/logger.cpp
  kirill_tolstobrov/logger.hpp
  kirill_tolstobrov/main.cpp
  kirill_tolstobrov/prog
Labels: task_07

#138 roman_kuprii/task_08
  roman_kuprii/Makefile
  roman_kuprii/graph.cpp
  roman_kuprii/graph.hpp
  roman_kuprii/graph_generator.cpp
  roman_kuprii/graph_printing.cpp
  roman_kuprii/graph_printing.hpp
  roman_kuprii/graph_traversal_controller.cpp
  roman_kuprii/graph_traversal_controller.hpp
  roman_kuprii/graph_traverser.cpp
  roman_kuprii/graph_traverser.hpp
  roman_kuprii/logging_helping.hpp
  roman_kuprii/main.cpp
  roman_kuprii/prog
Labels: task_08

#120 anton_potapov/task_05
  .gitignore
  anton_potapov/README.md
  anton_potapov/config.cpp
  anton_potapov/config.hpp
  anton_potapov/graph.cpp
  anton_potapov/graph.hpp
  anton_potapov/graph_create.cpp
  anton_potapov/graph_generator.cpp
  anton_potapov/graph_generator.hpp
  anton_potapov/graph_printer.cpp
  anton_potapov/graph_printer.hpp
  anton_potapov/graph_traverser.cpp
  anton_potapov/graph_traverser.hpp
  anton_potapov/logger.cpp
  anton_potapov/logger.hpp
  anton_potapov/main.cpp
Labels: task_05

#153 nikolai_chernyshov/task_08
  nikolai_chernyshov/Makefile
  nikolai_chernyshov/graph.cpp
  nikolai_chernyshov/graph.hpp
  nikolai_chernyshov/graph_generator.cpp
  nikolai_chernyshov/graph_path.hpp
  nikolai_chernyshov/graph_printer.cpp
  nikolai_chernyshov/graph_printer.hpp
  nikolai_chernyshov/graph_traversal_controller.cpp
  nikolai_chernyshov/graph_traversal_controller.hpp
  nikolai_chernyshov/graph_traverser.cpp
  nikolai_chernyshov/graph_traverser.hpp
  nikolai_chernyshov/main.cpp
  nikolai_chernyshov/main.o
Labels: task_08

#151 anton_gadzikovskiy/task_06
  anton_gadzikovskiy/a.exe
  anton_gadzikovskiy/graph_generator.cpp
  anton_gadzikovskiy/graph_generator.hpp
Labels: task_06

#152 kirill_tolstobrov/task_08
  kirill_tolstobrov/graph.cpp
  kirill_tolstobrov/graph.hpp
  kirill_tolstobrov/graph_path.hpp
  kirill_tolstobrov/graph_printer.cpp
  kirill_tolstobrov/graph_printer.hpp
  kirill_tolstobrov/graph_traversal_controller.cpp
  kirill_tolstobrov/graph_traversal_controller.hpp
  kirill_tolstobrov/graph_traverser.cpp
  kirill_tolstobrov/graph_traverser.hpp
  kirill_tolstobrov/main.cpp
  kirill_tolstobrov/prog
Labels: task_08

#149 dana_stepina/task_06
  dana_stepina/Makefile
  dana_stepina/graph.cpp
  dana_stepina/graph.hpp
  dana_stepina/graph_generator.cpp
  dana_stepina/graph_generator.hpp
  dana_stepina/graph_printer.cpp
  dana_stepina/main
Labels: task_06

#161 anton_gadzikovskiy/task_07
  anton_gadzikovskiy/a.exe
  anton_gadzikovskiy/graph_generation_controller.cpp
  anton_gadzikovskiy/graph_generation_controller.hpp
  anton_gadzikovskiy/graph_generator.cpp
  anton_gadzikovskiy/graph_generator.hpp
  anton_gadzikovskiy/main.cpp
Labels: task_07

#160 shamil_latypov/task_06
  shamil_latypov/graph.cpp
  shamil_latypov/graph.hpp
  shamil_latypov/graph_generator.cpp
  shamil_latypov/graph_generator.hpp
  shamil_latypov/main
  shamil_latypov/main.cpp
Labels: task_06

#156 tamara_gadieva/task_06
  .gitignore
  tamara_gadieva/graph_generator.cpp
  tamara_gadieva/graph_generator.hpp
  tamara_gadieva/graph_printing.cpp
  tamara_gadieva/main
  tamara_gadieva/main.cpp
Labels: task_06

#76 alexey_matveev/task_05
  .gitignore
  matveev_alexey/config.hpp
  matveev_alexey/graph.cpp
  matveev_alexey/graph.hpp
  matveev_alexey/graph.json
  matveev_alexey/graph_generator.cpp
  matveev_alexey/graph_generator.hpp
  matveev_alexey/graph_printer.cpp
  matveev_alexey/graph_printer.hpp
  matveev_alexey/logger.cpp
  matveev_alexey/logger.hpp
  matveev_alexey/main.cpp
  matveev_alexey/task
  matveev_alexey/task.cpp
Labels: task_05

#150 robert_gaisin/task_06
  robert_gaisin/Makefile
  robert_gaisin/graph
  robert_gaisin/graph_generator.cpp
  robert_gaisin/graph_generator.hpp
  robert_gaisin/graph_printer.cpp
  robert_gaisin/main.cpp
Labels: task_06

#164 tamara_gadieva/task_07
  tamara_gadieva/graph_generation_controller.cpp
  tamara_gadieva/graph_generation_controller.hpp
  tamara_gadieva/graph_generator.cpp
  tamara_gadieva/logger.cpp
  tamara_gadieva/logger.hpp
  tamara_gadieva/main
  tamara_gadieva/main.cpp
Labels: task_07

#167 Alexey matveev/task 06
  matveev_alexey/graph_generator.cpp
  matveev_alexey/graph_generator.hpp
  matveev_alexey/task
Labels: task_06

#165 shamil_latypov/task_07
  shamil_latypov/graph.cpp
  shamil_latypov/graph.hpp
  shamil_latypov/graph_generation_controller.cpp
  shamil_latypov/graph_generation_controller.hpp
  shamil_latypov/graph_generator.cpp
  shamil_latypov/graph_generator.hpp
  shamil_latypov/logger.cpp
  shamil_latypov/logger.hpp
  shamil_latypov/main
  shamil_latypov/main.cpp
Labels: task_07

#159 dana_stepina/task_07
  dana_stepina/graph.json
  dana_stepina/graph_generation_controller.cpp
  dana_stepina/graph_generation_controller.hpp
  dana_stepina/logger.cpp
  dana_stepina/logger.hpp
  dana_stepina/main
  dana_stepina/main.cpp
Labels: task_07

#162 anton_potapov/task_06
  anton_potapov/graph_generator.cpp
  anton_potapov/graph_generator.hpp
Labels: task_06

#166 dana_stepina/task_08
  dana_stepina/graph_path.hpp
  dana_stepina/graph_printer.cpp
  dana_stepina/graph_printer.hpp
  dana_stepina/graph_traversal_controller.cpp
  dana_stepina/graph_traversal_controller.hpp
  dana_stepina/graph_traverser.cpp
  dana_stepina/graph_traverser.hpp
  dana_stepina/main
  dana_stepina/main.cpp
Labels: task_08

#171 tamara_gadieva/task_08
  tamara_gadieva/graph.hpp
  tamara_gadieva/graph_printing.cpp
  tamara_gadieva/graph_printing.hpp
  tamara_gadieva/graph_traversal_controller.cpp
  tamara_gadieva/graph_traversal_controller.hpp
  tamara_gadieva/graph_traverser.cpp
  tamara_gadieva/graph_traverser.hpp
  tamara_gadieva/main
  tamara_gadieva/main.cpp
Labels: task_08

#168 robert_gaisin/task_07
  robert_gaisin/Makefile
  robert_gaisin/graph
  robert_gaisin/graph_generation_controller.cpp
  robert_gaisin/graph_generation_controller.hpp
  robert_gaisin/graph_generator.cpp
  robert_gaisin/graph_generator.hpp
  robert_gaisin/logger.cpp
  robert_gaisin/logger.hpp
  robert_gaisin/main.cpp
Labels: task_07

#177 shamil_latypov/task_08
  shamil_latypov/graph.cpp
  shamil_latypov/graph.hpp
  shamil_latypov/graph_path.cpp
  shamil_latypov/graph_path.hpp
  shamil_latypov/graph_traversal_controller.cpp
  shamil_latypov/graph_traversal_controller.hpp
  shamil_latypov/graph_traverser.cpp
  shamil_latypov/graph_traverser.hpp
  shamil_latypov/main
  shamil_latypov/main.cpp
Labels: task_08

#176 alexey_matveev/task7
  matveev_alexey/graph_generation_controller.cpp
  matveev_alexey/graph_generation_controller.hpp
  matveev_alexey/logger.cpp
  matveev_alexey/logger.hpp
  matveev_alexey/main.cpp
  matveev_alexey/task
Labels: task_07

#154 xieyu_wang/task_05
  .gitignore
  xieyu_wang/Config.cpp
  xieyu_wang/Config.hpp
  xieyu_wang/Edge.cpp
  xieyu_wang/Edge.hpp
  xieyu_wang/Graph.cpp
  xieyu_wang/Graph.hpp
  xieyu_wang/GraphGenerator.cpp
  xieyu_wang/GraphGenerator.hpp
  xieyu_wang/GraphPrinter.cpp
  xieyu_wang/GraphPrinter.hpp
  xieyu_wang/Logger.cpp
  xieyu_wang/Logger.hpp
  xieyu_wang/LoggingHelper.cpp
  xieyu_wang/LoggingHelper.hpp
  xieyu_wang/Task_05.exe
  xieyu_wang/Vertex.cpp
  xieyu_wang/Vertex.hpp
  xieyu_wang/main
  xieyu_wang/main.cpp
Labels: task_05

#163 nikolay arbuzov/task04
  nikolay_arbuzov/graph.json
  nikolay_arbuzov/main
  nikolay_arbuzov/main.cpp
Labels: task_04

#172 anton_potapov/task_07
  anton_potapov/graph_generation_controller.cpp
  anton_potapov/graph_generation_controller.hpp
  anton_potapov/graph_input_handler.cpp
  anton_potapov/graph_input_handler.hpp
  anton_potapov/log_messages_generator.cpp
  anton_potapov/log_messages_generator.hpp
  anton_potapov/logger.cpp
  anton_potapov/logger.hpp
  anton_potapov/main.cpp
Labels: task_07

#71 alexey_mesheryakov/task_04
  alexey_mesheryakov/a.out
  alexey_mesheryakov/gr
  alexey_mesheryakov/graph.cpp
  alexey_mesheryakov/graph.hpp
  alexey_mesheryakov/graph.json
  alexey_mesheryakov/graph_generator.cpp
  alexey_mesheryakov/graph_generator.hpp
  alexey_mesheryakov/graph_printer.cpp
  alexey_mesheryakov/graph_printer.hpp
  alexey_mesheryakov/main.cpp
Labels: task_04

#119 maxim_grabovskiy/task_04
  maxim_grabovskiy/a.out
  maxim_grabovskiy/graph.json
  maxim_grabovskiy/main.cpp
Labels: task_04

#181 nikolay_arbuzov/task05
  .gitignore
  nikolay_arbuzov/Makefile
  nikolay_arbuzov/config.hpp
  nikolay_arbuzov/graph.cpp
  nikolay_arbuzov/graph.hpp
  nikolay_arbuzov/graph.json
  nikolay_arbuzov/graph_generator.cpp
  nikolay_arbuzov/graph_generator.hpp
  nikolay_arbuzov/graph_json_printing.cpp
  nikolay_arbuzov/graph_json_printing.hpp
  nikolay_arbuzov/graph_printing.cpp
  nikolay_arbuzov/graph_printing.hpp
  nikolay_arbuzov/logger.cpp
  nikolay_arbuzov/logger.hpp
  nikolay_arbuzov/main
  nikolay_arbuzov/main.cpp
  nikolay_arbuzov/main.o
Labels: task_05

#183 nikolay arbuzov/task06
  nikolay_arbuzov/Makefile
  nikolay_arbuzov/graph.hpp
  nikolay_arbuzov/graph_generator.cpp
  nikolay_arbuzov/graph_generator.hpp
  nikolay_arbuzov/main.o
Labels: task_06

#170 alexey_mesheryakov/task_06
  alexey_mesheryakov/a.out
  alexey_mesheryakov/graph.cpp
  alexey_mesheryakov/graph.hpp
  alexey_mesheryakov/graph_generator.cpp
  alexey_mesheryakov/graph_generator.hpp
  alexey_mesheryakov/graph_printer.cpp
  alexey_mesheryakov/main.cpp
Labels: task_06

#179 alexey_mesheryakov/task_07
  alexey_mesheryakov/a.out
  alexey_mesheryakov/graph_generation_controller.cpp
  alexey_mesheryakov/graph_generation_controller.hpp
  alexey_mesheryakov/logger.cpp
  alexey_mesheryakov/logger.hpp
  alexey_mesheryakov/main.cpp
Labels: task_07

#186 nikolay_arbuzov/task07
  nikolay_arbuzov/graph_generation_controller.cpp
  nikolay_arbuzov/graph_generation_controller.hpp
  nikolay_arbuzov/graph_generator.cpp
  nikolay_arbuzov/graph_json_printing.cpp
  nikolay_arbuzov/graph_printing.cpp
  nikolay_arbuzov/logger.cpp
  nikolay_arbuzov/logger.hpp
  nikolay_arbuzov/main.cpp
  nikolay_arbuzov/main.o
Labels: task_07

#182 xieyu_wang/task_06
  xieyu_wang/Graph.cpp
  xieyu_wang/Graph.hpp
  xieyu_wang/GraphGenerator.cpp
  xieyu_wang/GraphGenerator.hpp
  xieyu_wang/Logger.cpp
  xieyu_wang/LoggingHelper.cpp
  xieyu_wang/Task_05.exe
  xieyu_wang/main.exe
Labels: task_06

#155 alexander_setyaev/task_04
  setyaev_alexander/a.out
  setyaev_alexander/edge.cpp
  setyaev_alexander/edge.hpp
  setyaev_alexander/graph.cpp
  setyaev_alexander/graph.hpp
  setyaev_alexander/graph.json
  setyaev_alexander/graph_json_printing.cpp
  setyaev_alexander/graph_json_printing.hpp
  setyaev_alexander/main.cpp
  setyaev_alexander/makefile
  setyaev_alexander/vertex.cpp
  setyaev_alexander/vertex.hpp
Labels: task_04

#175 maxim_grabovskiy/task_05
  maxim_grabovskiy/config.hpp
  maxim_grabovskiy/graph.cpp
  maxim_grabovskiy/graph.hpp
  maxim_grabovskiy/graph_generator.cpp
  maxim_grabovskiy/graph_generator.hpp
  maxim_grabovskiy/graph_json_printing.cpp
  maxim_grabovskiy/graph_json_printing.hpp
  maxim_grabovskiy/graph_printing.cpp
  maxim_grabovskiy/graph_printing.hpp
  maxim_grabovskiy/logger.cpp
  maxim_grabovskiy/logger.hpp
  maxim_grabovskiy/main.cpp
Labels: task_05

#187 alexey_matveev/task_08
  matveev_alexey/graph_generator.cpp
  matveev_alexey/graph_path.cpp
  matveev_alexey/graph_path.hpp
  matveev_alexey/graph_traversal_controller.cpp
  matveev_alexey/graph_traversal_controller.hpp
  matveev_alexey/graph_traverser.cpp
  matveev_alexey/graph_traverser.hpp
  matveev_alexey/main.cpp
  matveev_alexey/task
Labels: task_08

#184 anton_potapov/task_08
  anton_potapov/concurrent_controller.cpp
  anton_potapov/concurrent_controller.hpp
  anton_potapov/config.hpp
  anton_potapov/graph_generation_controller.cpp
  anton_potapov/graph_generation_controller.hpp
  anton_potapov/graph_generator.cpp
  anton_potapov/graph_input_handler.hpp
  anton_potapov/graph_path.cpp
  anton_potapov/graph_path.hpp
  anton_potapov/graph_printer.cpp
  anton_potapov/graph_printer.hpp
  anton_potapov/graph_traversal_controller.cpp
  anton_potapov/graph_traversal_controller.hpp
  anton_potapov/graph_traverser.cpp
  anton_potapov/graph_traverser.hpp
  anton_potapov/log_messages_generator.cpp
  anton_potapov/log_messages_generator.hpp
  anton_potapov/logger.hpp
  anton_potapov/main.cpp
Labels: task_08

#185 xieyu_wang/task_07
  xieyu_wang/Graph.cpp
  xieyu_wang/GraphGenerator.cpp
  xieyu_wang/GraphGenerator.hpp
  xieyu_wang/GraphGeneratorController.cpp
  xieyu_wang/GraphGeneratorController.hpp
  xieyu_wang/Logger.cpp
  xieyu_wang/main.cpp
Labels: task_07

#191 nikolay arbuzov/task08
  nikolay_arbuzov/graph.cpp
  nikolay_arbuzov/graph.hpp
  nikolay_arbuzov/graph_path.hpp
  nikolay_arbuzov/graph_printing.cpp
  nikolay_arbuzov/graph_printing.hpp
  nikolay_arbuzov/graph_traversal_controller.cpp
  nikolay_arbuzov/graph_traversal_controller.hpp
  nikolay_arbuzov/graph_traverser.cpp
  nikolay_arbuzov/graph_traverser.hpp
  nikolay_arbuzov/main.cpp
  nikolay_arbuzov/main.o
Labels: task_08

#39 danil_dyachenko/task_02
  danil_dyachenko/HelloWorld
  danil_dyachenko/HelloWorld.cpp
  danil_dyachenko/README.md
  danil_dyachenko/graph_gen
  danil_dyachenko/graph_gen.cpp
  danil_dyachenko/my_graph.json
  danil_dyachenko/screenshot.png
Labels: task_02, task_03

#189 alexander_setyaev/task_05
  setyaev_alexander/a.out
  setyaev_alexander/config.hpp
  setyaev_alexander/edge.cpp
  setyaev_alexander/edge.hpp
  setyaev_alexander/graph.cpp
  setyaev_alexander/graph.hpp
  setyaev_alexander/graph_generator.cpp
  setyaev_alexander/graph_generator.hpp
  setyaev_alexander/graph_json_printing.cpp
  setyaev_alexander/graph_json_printing.hpp
  setyaev_alexander/graph_printing.cpp
  setyaev_alexander/graph_printing.hpp
  setyaev_alexander/logger.cpp
  setyaev_alexander/logger.hpp
  setyaev_alexander/main.cpp
  setyaev_alexander/makefile
  setyaev_alexander/vertex.cpp
  setyaev_alexander/vertex.hpp
Labels: task_05

#198 alexey_mesheryakov/task_8
  alexey_mesheryakov/a.out
  alexey_mesheryakov/graph.cpp
  alexey_mesheryakov/graph.hpp
  alexey_mesheryakov/graph_generation_controller.hpp
  alexey_mesheryakov/graph_path.hpp
  alexey_mesheryakov/graph_printer.cpp
  alexey_mesheryakov/graph_printer.hpp
  alexey_mesheryakov/graph_traversal_controller.cpp
  alexey_mesheryakov/graph_traversal_controller.hpp
  alexey_mesheryakov/graph_traverser.cpp
  alexey_mesheryakov/graph_traverser.hpp
  alexey_mesheryakov/main.cpp
Labels: task_08

#190 maxim_grabovskiy/task_06
  maxim_grabovskiy/graph.cpp
  maxim_grabovskiy/graph.hpp
  maxim_grabovskiy/graph_generator.cpp
  maxim_grabovskiy/graph_generator.hpp
  maxim_grabovskiy/graph_printing.cpp
  maxim_grabovskiy/main.cpp
Labels: task_06

#192 robert_gaisin/task_09
  robert_gaisin/Makefile
  robert_gaisin/config.cpp
  robert_gaisin/config.hpp
  robert_gaisin/game.cpp
  robert_gaisin/game.hpp
  robert_gaisin/game_generator.cpp
  robert_gaisin/game_generator.hpp
  robert_gaisin/graph
  robert_gaisin/graph.cpp
  robert_gaisin/graph.hpp
  robert_gaisin/graph_path.hpp
  robert_gaisin/graph_printer.cpp
  robert_gaisin/graph_printer.hpp
  robert_gaisin/graph_traversal_controller.cpp
  robert_gaisin/graph_traversal_controller.hpp
  robert_gaisin/graph_traverser.cpp
  robert_gaisin/graph_traverser.hpp
  robert_gaisin/main.cpp
  robert_gaisin/map.json
Labels: task_09
