Repository Friend-LGA/msu_course_cpp_323, pull requests merged in 2021-11, with the labels that each got.

#64 novikov_dmitry/task_04
  02_knight_and_princess/novikov_dmitry/Graph.json
  02_knight_and_princess/novikov_dmitry/graph.hpp
  02_knight_and_princess/novikov_dmitry/graph_generation.hpp
  02_knight_and_princess/novikov_dmitry/main.cpp
  02_knight_and_princess/novikov_dmitry/task_02.cpp
Labels: task_04

#69 tevfik_aksoy/task_04
  02_knight_and_princess/tevfik_aksoy/graph.json
  02_knight_and_princess/tevfik_aksoy/main
  02_knight_and_princess/tevfik_aksoy/main.cpp
Labels: task_04

#79 anton_gadzikovskiy/task_01
  01_hello_world/anton_gadzikovskiy/README.md
  01_hello_world/anton_gadzikovskiy/hello_world
  01_hello_world/anton_gadzikovskiy/hello_world.cpp
  01_hello_world/anton_gadzikovskiy/screenshot.jpg
Labels: task_01

#47 xieyu_wang/task_02
  02_knight_and_princess/xieyu_wang/Graph.json
  02_knight_and_princess/xieyu_wang/main
  02_knight_and_princess/xieyu_wang/main.cpp
Labels: task_02, task_03

#29 kirill_tolstobrov/task_02
  02_knight_and_princess/kirill_tolstobrov/graph.json
  02_knight_and_princess/kirill_tolstobrov/main.cpp
  02_knight_and_princess/kirill_tolstobrov/prog
Labels: task_02, task_03

#60 dana_stepina/task_02
  02_knight_and_princess/dana_stepina/graph.json
  02_knight_and_princess/dana_stepina/main
  02_knight_and_princess/dana_stepina/main.cpp
Labels: task_02, task_03

#40 nikolai_chernyshov/task_02
  02_knight_and_princess/nikolai_chernyshov/Makefile
  02_knight_and_princess/nikolai_chernyshov/README.md
  02_knight_and_princess/nikolai_chernyshov/graph.json
  02_knight_and_princess/nikolai_chernyshov/main.cpp
  02_knight_and_princess/nikolai_chernyshov/main.o
Labels: task_02, task_03

#59 shamil_latypov/task_02
  02_knight_and_princess/shamil_latypov/main
  02_knight_and_princess/shamil_latypov/main.cpp
  02_knight_and_princess/shamil_latypov/out.json
Labels: task_02, task_03

#73 alexey_matveev/task 02
  matveev_alexey/README.md
  matveev_alexey/hello_world
  matveev_alexey/hello_world.cpp
  matveev_alexey/screenshot.jpg
  matveev_alexey/task2
  matveev_alexey/task2.cpp
Labels: task_02

#90 tevfik_aksoy/task_05
  .gitignore
  tevfik_aksoy/graph.cpp
  tevfik_aksoy/graph.hpp
  tevfik_aksoy/graph_generator.cpp
  tevfik_aksoy/graph_generator.hpp
  tevfik_aksoy/graph_printer.cpp
  tevfik_aksoy/graph_printer.hpp
  tevfik_aksoy/logger.cpp
  tevfik_aksoy/logger.hpp
  tevfik_aksoy/main
  tevfik_aksoy/main.cpp
Labels: task_05

#95 shamil_latypov/task_04
  shamil_latypov/main
  shamil_latypov/main.cpp
  shamil_latypov/out.json
Labels: task_04

#74 alexey_matveev/task_03
  matveev_alexey/graph.json
  matveev_alexey/task2
  matveev_alexey/task3
  matveev_alexey/task3.cpp
Labels: task_03

#80 anton_gadzikovskiy/task_02
  anton_gadzikovskiy/README.md
  anton_gadzikovskiy/a.exe
  anton_gadzikovskiy/graph.json
  anton_gadzikovskiy/graph_generator.cpp
  anton_gadzikovskiy/hello_world
  anton_gadzikovskiy/hello_world.cpp
  anton_gadzikovskiy/screenshot.jpg
Labels: task_02, task_03

#92 novikov_dmitry/task_05
  .gitignore
  novikov_dmitry/graph.cpp
  novikov_dmitry/graph.hpp
  novikov_dmitry/graph_generation.cpp
  novikov_dmitry/graph_generation.hpp
  novikov_dmitry/graph_printer.cpp
  novikov_dmitry/graph_printer.hpp
  novikov_dmitry/logger.cpp
  novikov_dmitry/logger.hpp
  novikov_dmitry/main.cpp
Labels: task_05

#81 roman kuprii/task 05
  .gitignore
  roman_kuprii/Makefile
  roman_kuprii/graph.cpp
  roman_kuprii/graph.hpp
  roman_kuprii/graph.json
  roman_kuprii/graph_generating.cpp
  roman_kuprii/graph_generating.hpp
  roman_kuprii/graph_printing.cpp
  roman_kuprii/graph_printing.hpp
  roman_kuprii/logger.cpp
  roman_kuprii/logger.hpp
  roman_kuprii/logging_helping.hpp
  roman_kuprii/main.cpp
  roman_kuprii/prog
Labels: task_05

#99 maxim_grabovskiy/task_01
  maxim_grabovskiy/README.md
  maxim_grabovskiy/hello_world
  maxim_grabovskiy/hello_world.cpp
  maxim_grabovskiy/screenshot.png
Labels: task_01

#103 novikov_dmitry/task_06_preparation
  novikov_dmitry/graph_generator.cpp
  novikov_dmitry/graph_generator.hpp
  novikov_dmitry/logger.cpp
  novikov_dmitry/main.cpp
  novikov_dmitry/main.exe
Labels: task_05

#98 kirill_tolstobrov/task_04
  kirill_tolstobrov/graph.json
  kirill_tolstobrov/main.cpp
  kirill_tolstobrov/prog
Labels: task_04

#105 maxim_grabovskiy/task 02
  maxim_grabovskiy/README.md
  maxim_grabovskiy/a.out
  maxim_grabovskiy/hello_world
  maxim_grabovskiy/hello_world.cpp
  maxim_grabovskiy/main.cpp
  maxim_grabovskiy/screenshot.png
Labels: task_02

#75 alexey_matveev/task_04
  matveev_alexey/graph.json
  matveev_alexey/task
  matveev_alexey/task.cpp
  matveev_alexey/task3
  matveev_alexey/task3.cpp
Labels: task_04

#96 nikolay_shapurov/task_02
  nikolay_shapurov/task_02/compile.sh
  nikolay_shapurov/task_02/graph
  nikolay_shapurov/task_02/graph.cpp
  nikolay_shapurov/task_02/graph.hpp
  nikolay_shapurov/task_02/main.cpp
Labels: task_02

#97 nikolay_shapurov/task_03
  nikolay_shapurov/README.md
  nikolay_shapurov/compile.sh
  nikolay_shapurov/graph
  nikolay_shapurov/graph.cpp
  nikolay_shapurov/graph.hpp
  nikolay_shapurov/graph.json
  nikolay_shapurov/graph_printer.cpp
  nikolay_shapurov/graph_printer.hpp
  nikolay_shapurov/hello_world
  nikolay_shapurov/hello_world.cpp
  nikolay_shapurov/main.cpp
  nikolay_shapurov/picture.png
Labels: task_03

#101 novikov_dmitry/task_06
  novikov_dmitry/graph_generation_controller.cpp
  novikov_dmitry/graph_generation_controller.hpp
  novikov_dmitry/graph_generator.cpp
  novikov_dmitry/graph_generator.hpp
  novikov_dmitry/main.cpp
Labels: task_06

#107 roman_kuprii/task_06
  roman_kuprii/Makefile
  roman_kuprii/graph_generating.hpp
  roman_kuprii/graph_generation.cpp
  roman_kuprii/graph_generation.hpp
  roman_kuprii/graph_generation_controller.cpp
  roman_kuprii/graph_generation_controller.hpp
  roman_kuprii/logging_helping.hpp
  roman_kuprii/main.cpp
  roman_kuprii/prog
Labels: task_06

#106 maxim_grabovskiy/task_03
  maxim_grabovskiy/a.out
  maxim_grabovskiy/graph.json
  maxim_grabovskiy/main.cpp
Labels: task_03

#108 tevfik_aksoy/task_07
  tevfik_aksoy/graph_generation_controller.cpp
  tevfik_aksoy/graph_generation_controller.hpp
  tevfik_aksoy/graph_generator.cpp
  tevfik_aksoy/graph_generator.hpp
  tevfik_aksoy/logger.cpp
  tevfik_aksoy/logger.hpp
  tevfik_aksoy/main
  tevfik_aksoy/main.cpp
Labels: task_07
